@startsalt "基本信息表单"
{
    {
        { 员工姓名 | "输入员工工号或姓名进行搜索" } | { 产假开始日期 <color:red>*</color> | {"2025/10/22" | [📅]} }
        
        { 选择城市 | ^上海^ } | { 产假结束日期 | { "2026/03/28" | [📅] } }

        { 公司平均工资 <color:red>*</color> | "49000"   } | { 社保三倍上限 | "36921" }

        { 员工产前12月平均工资 <color:red>*</color> | "<color:grey><size:10>大于单位平均工资需填写</size></color>" } | { 政府发放金额 | "194450.60" }
        
        { 生产情况 | ^未选择^ } | { 生育胎数 | "1" }
    }
    
}
@endsalt