@startsalt "工资调整表单"
{
    {
        调整前 员工基本工资 | "输入调整前工资"
    } | {
        调整后 员工基本工资 | "输入调整后工资"
    } | {
        工资调整年月 | "YYYY/MM/DD"
    }

    {
        调整前 月度个人部分社保公积金合计 | "输入金额"
    } | {
        调整后 月度个人部分社保公积金合计 | "输入金额"
    } | {
        社保调整年月 | "YYYY/MM/DD"
    }
}
@endsalt
