@startsalt "需返还信息"
{
    {
        **需返还信息**
        
        { 请假开始时间 | "2025/10/22" } | { 请假结束时间 | "2026/04/12" }
        { 员工基本工资 <color:red>*</color> | 49000 } | { 月度个人部分社保公积金合计 <color:red>*</color> | { "月个人部分缴费金额" | [工资社保调整 👁️] } } 
    }
}
@endsalt
