@startsalt "需返还编辑"
{
    { 需返还编辑 | {
        [+ 手动增加扣减项] | [自动计算减扣项]
    }}

    {#
        | 减扣内容 | "发放Spot On" | 扣减金额 | "-100" | [删除]
        | 减扣内容 | "月弹性福利自费" | 扣减金额 | "300" | [删除]
        | 减扣内容 | "工会费 × 5个月(2025-11 - 2026-03)" | 扣减金额 | "250" | [删除]
        | 减扣内容 | "月度个人部分社保公积金合计 × 5个月(2025-11 - 2026-03)" | 扣减金额 | "23240.8" | [删除]
    }

}
@endsalt