@startsalt "页头"
{
    {
        ' 左右两栏布局，左边是标题，右边是退出按钮
        {
            ' 小标题
            🎉 <color:#a44d69>喜得贵子</color>
            ' 大标语
            <color:#5a2d43>喜迎新生命 · 产假津贴安心算</color>
        } | {
            [退出]
        }
    }
}
@endsalt