@startsalt "基础数据管理 - 产假规则"
{
    !include __fragment/基础数据管理-页头.puml

    {/ <b><color:#a44d69>📅 产假规则</color></b> | 💰 津贴规则 | 💸 返还规则 | 👥 员工信息 | 🧨 节假日 }

    {
        ' 左右两栏布局
        { [添加产假规则] } | { [📥 下载模板] | [📤 导入数据] | [📊 导出数据] }
    }

    {#
        | 城市 | 产假类型 | 流产类型 | 产假天数	| 是否遇法定节假日顺延 | 是否享受津贴 | 操作
        | 北京 | 多胞胎   | . | 15 | 是 | 是 | { [编辑] | [删除] }
        | 上海 | 法定产假 | . | 98 | 是 | 是 | { [编辑] | [删除] }
        | 佛山	 | 流产假  | 妊娠未满4个月流产 | 15 | 否 | 是 | { [编辑] | [删除] }
        | 北京 | 难产假	 | . | 15 | 否 | 是 | { [编辑] | [删除] }
        | 厦门	 | 晚育假/生育假/奖励假 | . | 30 | 否 | 是 | { [编辑] | [删除] }
    }
}
@endsalt