@startsalt "基础数据管理 - 员工信息"
{
    !include __fragment/基础数据管理-页头.puml

    {/ 📅 产假规则 | 💰 津贴规则 | 💸 返还规则 | <b><color:#a44d69>👥 员工信息</color></b> | 🧨 节假日 }

    {
        ' 左右两栏布局
        { [添加员工信息] } | { [📥 下载模板] | [📤 导入数据] | [📊 导出数据] }
    }

    {#
    编号 | 员工姓名 | 产前12月平均工资 | 基本工资  | 个人部分社保公积金合计 | 城市 | 操作
    1   | 李上海   | ¥12,821.79     | ¥20,000 | ¥4,648.16          | 上海  | { [编辑] | [删除] }
    }
}
@endsalt