@startsalt "基础数据管理 - 津贴规则"
{
    !include __fragment/基础数据管理-页头.puml

    {/ 📅 产假规则 | <b><color:#a44d69>💰 津贴规则</color></b> | 💸 返还规则 | 👥 员工信息 | 🧨 节假日 }

    {
        ' 左右两栏布局
        { [添加津贴规则] } | { [📥 下载模板] | [📤 导入数据] | [📊 导出数据] }
    }

    {#
        城市| 社平工资 | 津贴计算基数 | 津贴基数类型 | 津贴发放方式 | 产假政策 | 津贴政策 | 操作
        上海 | ¥12,307 | ¥49,000 | 平均工资 | 个人 | 法定产假98天（... | 汇至账户：个人；... | { [编辑] | [删除] }
        佛山 | ¥8,070 | ¥35,000 | 平均工资 | 企业 | 法定产假98天（... | 汇至账户：企业；... | { [编辑] | [删除] }
        北京 | ¥12,297 | ¥35,000 | 平均缴费工资 | 企业 | 法定产假98天（... | 汇至账户：企业；... | { [编辑] | [删除] }
    }
}
@endsalt