@startsalt "基础数据管理 - 节假日"
{
    !include __fragment/基础数据管理-页头.puml

    {/ 📅 产假规则 | 💰 津贴规则 | 💸 返还规则 | 👥 员工信息 | <b><color:#a44d69>🧨 节假日</b> }

    {
        ' 左右两栏布局
        { [📋 复制到上一年] | [📋 复制到下一年] | [◀ 上一年] | [下一年 ▶] | { 筛选年份： | ^2025^ } } | { [📥 下载模板] | [📤 导入数据] | [📊 导出数据] }
    }

    {#
        节日 | 日期 | 类型 | 是否为法定假日 | 操作
        元旦 | 2025-01-01 | 节假日 | 是 | { [编辑] | [新增] | [删除] }
        春节调休 | 2025-01-26 | 工作日 | 否 | { [编辑] | [新增] | [删除] }
        春节 | 2025-01-28 ~ 2025-02-04 (8天) | 节假日 | - | { [编辑] | [新增] | [删除] }
    }
    {
        <b>统计信息</b>
        {#
            节假日 | 调休工作日
            <color:blue>28</color> | <color:blue>5</color>
        }
    }
}
@endsalt