@startsalt "Tab - 选中基础数据管理"
{
    !include ../../__fragment/page-header.puml

    {/ 产假津贴计算 | 批量处理 | 智能助手 | <b><color:#a44d69>基础数据管理</color></b> }

    {
        🏙️ 基础数据管理
        {
            管理各城市的产假规则、津贴规则、返还规则和员工信息 | {筛选城市： | ^筛选城市...^ }
        }
    }
}
@endsalt